name: bluetooth_bms
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.1+13

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.1
  intl: ^0.19.0
  flutter_native_splash: ^2.3.11
  flutter_launcher_icons: ^0.13.1
  animated_text_kit: ^4.2.2
  dot_navigation_bar: ^1.0.2
  url_launcher: ^6.3.0
  flutter_blue_plus: ^1.35.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png

flutter_native_splash:
  color: "#000000"
  image: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/